service: kamal_test
image: muf-test/kamal_test

servers:
  web:
    - 91.134.11.49
ssh:
  user: ubuntu

registry:
  server: 62n770gh.gra7.container-registry.ovh.net
  username: "robot$muf-test+muftest"
  password: SgrWAsgMMAVvuKY8s6slxhTSCLg4SSgn

builder:
  arch: amd64

#proxy:
 # ssl: true
 # host: app.example.com